spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      # =================================
      - id: customers-rest-api
        uri: lb://customer-service
        predicates:
        - Path=/customers/**
        filters:
        - name: Hystrix
          args:
            name: customerFallback
            fallbackUri: forward:/fallback

server:
  port: 8080
